CC = gcc

# Voodoo for cleaning up dependencies generated by gcc -c -MMD -MP

REPDEP = sed -i -e '1s,\($*\)\.o[ :]*,\1.o \.$*.d: ,' \.$*.d

# C source

SRC = main.c xymod.c clap.c
OBJ = $(patsubst %.c, .%.o, $(SRC))
DEP = $(patsubst %.o, %.d, $(OBJ))

BIN = xysim

MFLAGS  = -std=c99 -march=native
WFLAGS  = -Wall -Wextra -Wconversion -pedantic-errors -Wno-maybe-uninitialized
DFLAGS  = -D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE
OFLAGS  = -O3 -flto=auto
LDFLAGS = -lraylib -lGL -lm -ldl -lrt -lX11
CFLAGS  = $(MFLAGS) $(OFLAGS) $(WFLAGS) $(DFLAGS)

RM = rm -f

.PHONY: all clean

all: $(BIN)

clean:
	$(RM) $(OBJ) $(DEP) $(BIN)

$(OBJ): .%.o: %.c
	$(CC) -c -MMD -MP $(CFLAGS) $< -o $@
	@$(REPDEP)

$(BIN): $(OBJ)
	$(CC) $(OBJ) $(CFLAGS) $(LDFLAGS) -o $(BIN)

-include $(DEP)
